/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Taxonomy
 * Id: 340ea7fb-9fcc-4cce-9840-f4ca149907a4
 * Codename: taxonomy
 */
export type Taxonomy = 'for_consumers__b2c_' | 'for_other_businesses__b2b_';
