/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 */
export const contentTypeSnippets = {
    /**
     * SEO metadata
     */
    seo_metadata: {
        codename: 'seo_metadata',
        id: '508cbaf0-0a75-43c5-9386-7c972ab55d82',
        externalId: undefined,
        name: 'SEO metadata',
        elements: {
            /**
             * Meta title (text)
             *
             * This is a simple text field. It defines the title for your SEO metadata (and can be different than the name in Kontent.ai). Text fields don't store any formatting.
             */
            seo_metadata__meta_title: {
                codename: 'seo_metadata__meta_title',
                id: 'e295e0be-3d12-4fcc-b6b9-a308b7307bce',
                externalId: undefined,
                name: 'Meta title',
                required: false,
                type: 'text'
            },

            /**
             * Meta description (text)
             *
             * This is a simple text field. It defines the description for your SEO metadata. Text fields don't store any formatting.
             */
            seo_metadata__meta_description: {
                codename: 'seo_metadata__meta_description',
                id: 'a6d71176-bd66-42ae-92b1-9d1d4e2c8181',
                externalId: undefined,
                name: 'Meta description',
                required: false,
                type: 'text'
            }
        }
    }
} as const;
