/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 */
export const contentTypes = {
    /**
     * Event
     */
    event: {
        codename: 'event',
        id: 'b31c78db-966e-425c-8179-60a0eb0e7eaa',
        externalId: undefined,
        name: 'Event',
        elements: {
            /**
             * Date (date_time)
             */
            date: {
                codename: 'date',
                id: '0a7ad709-3173-4b1b-af15-92cea295e742',
                externalId: undefined,
                name: 'Date',
                required: true,
                type: 'date_time'
            },

            /**
             * Description (text)
             */
            description: {
                codename: 'description',
                id: '8416df8c-6f78-42a9-9322-e0e8821c28ad',
                externalId: undefined,
                name: 'Description',
                required: false,
                type: 'text'
            },

            /**
             * Image (asset)
             */
            image: {
                codename: 'image',
                id: '0ff87f53-0391-49d4-ac16-d000194491d6',
                externalId: undefined,
                name: 'Image',
                required: false,
                type: 'asset'
            },

            /**
             * Location (modular_content)
             */
            location: {
                codename: 'location',
                id: '5ebc6728-7212-4940-8b9b-746675318a21',
                externalId: undefined,
                name: 'Location',
                required: true,
                type: 'modular_content'
            },

            /**
             * Price (number)
             */
            price: {
                codename: 'price',
                id: '3ddf4fe2-e312-4397-a758-2f25027ea992',
                externalId: undefined,
                name: 'Price',
                required: false,
                type: 'number'
            },

            /**
             * Sold Out (multiple_choice)
             */
            sold_out: {
                codename: 'sold_out',
                id: 'cf91fb2b-3773-47b5-bcca-766235eb4834',
                externalId: undefined,
                name: 'Sold Out',
                required: false,
                type: 'multiple_choice',
                options: {
                    yes: {
                        name: 'Yes',
                        id: 'aabbb11e-3c72-448a-aff5-3fbec474e59a',
                        codename: 'yes',
                        externalId: undefined
                    },
                    no: {
                        name: 'No',
                        id: 'bd3f7a0a-06a1-4f8a-859f-4e7317b0cfb4',
                        codename: 'no',
                        externalId: undefined
                    }
                }
            },

            /**
             * Ticketing url (text)
             */
            ticketing_url: {
                codename: 'ticketing_url',
                id: 'd5f9e5b7-721b-4326-b19d-eade593a997b',
                externalId: undefined,
                name: 'Ticketing url',
                required: false,
                type: 'text'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: '7e29f745-bf67-4ad8-8682-c4b388f5e1b5',
                externalId: undefined,
                name: 'Title',
                required: true,
                type: 'text'
            }
        }
    },

    /**
     * Location
     */
    location: {
        codename: 'location',
        id: '7a7d19cf-692d-4f14-ad23-f0b43f187854',
        externalId: undefined,
        name: 'Location',
        elements: {
            /**
             * GPS coordinates (text)
             */
            gps_coordinates: {
                codename: 'gps_coordinates',
                id: 'c41469ae-4b42-4544-b051-d9e4dbd84449',
                externalId: undefined,
                name: 'GPS coordinates',
                required: false,
                type: 'text'
            },

            /**
             * Name (text)
             */
            name: {
                codename: 'name',
                id: 'f8dceac8-ffa0-40e6-8135-67a48c2a1dac',
                externalId: undefined,
                name: 'Name',
                required: true,
                type: 'text'
            }
        }
    }
} as const;
