/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 */
export const taxonomies = {
    /**
     * Taxonomy
     */
    taxonomy: {
        codename: 'taxonomy',
        id: '340ea7fb-9fcc-4cce-9840-f4ca149907a4',
        externalId: undefined,
        name: 'Taxonomy',
        terms: {
            for_consumers__b2c_: {
                codename: 'for_consumers__b2c_',
                id: 'c9e93cec-f80c-43a0-9b5d-3c6f9594d3fd',
                externalId: undefined,
                name: 'For consumers (B2C)',
                terms: {}
            },
            for_other_businesses__b2b_: {
                codename: 'for_other_businesses__b2b_',
                id: '1668c307-e2ac-4b9d-ab43-cad7416056b0',
                externalId: undefined,
                name: 'For other businesses (B2B)',
                terms: {}
            }
        }
    }
} as const;
